services:
  psql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: osaka 
      POSTGRES_PASSWORD: osaka 
      POSTGRES_DB: osaka 
    ports:
      - 5432:5432
    volumes:
      - ./docker-volume/psql:/var/lib/psql
    networks:
      - osaka-net

networks:
  osaka-net:
    driver: bridge
